# SIS:AUTO_GENERATED: Remove this line if you edit the file, otherwise it will be overwritten
add_subdirectory(test.component.dirent)
add_subdirectory(test.component.glob)
add_subdirectory(test.component.unistd.mkdtemp)
add_subdirectory(test.component.unistd.mkstemp)
add_subdirectory(test.component.unistd.usleep)
